- type: job
  parent: CMJobBase
  id: CMCargoTech
  name: cm-job-name-cargotech
  description: cm-job-description-cargotech
  playTimeTracker: CMJobCargoTech
  startingGear: CMGearCargoTech
  icon: "CMJobIconCargoTech"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-qm
  accessGroups:
  - CMCargoTech
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      construction: 1
      firearms: 1
      powerLoader: 2

- type: startingGear
  id: CMGearCargoTech
  equipment:
    jumpsuit: CMJumpsuitCargoTech
    back: CMSatchelMarineTech
    shoes: CMBootsBlack
    head: CMHeadCapCargo
    gloves: CMHandsInsulated
    id: CMIDCardCargoTech
    ears: CMHeadsetRequisition
    pocket1: CMPouchGeneralMedium
#    belt: TODO CM14 M276 Pattern General Pistol Holster Rig Filled

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointCargoTech
  name: cargo tech spawn point
  components:
  - type: SpawnPoint
    job_id: CMCargoTech
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: cargo_tech

- type: playTimeTracker
  id: CMJobCargoTech
