- type: job
  parent: CMJobSquadBase
  id: CMCombatTech
  name: cm-job-name-combat-tech
  description: cm-job-description-combat-tech
  playTimeTracker: CMJobCombatTech
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMSquad
    time: 3600 # 1 hour
  startingGear: CMGearCombatTech
  icon: "CMJobIconCombatTech"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-sl
  accessGroups:
  - CombatTech
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      constructiopn: 2
      engineer: 2
      firearms: 1
      jtac: 1
      vehicle: 1
    - type: CMVendorUser
      points: 45

- type: startingGear
  id: CMGearCombatTech
  equipment:
    jumpsuit: CMJumpsuitMarineEngineer # TODO CM14 all squad roles should spawn with no jumpsuit but still have clothes on
    back: CMSatchelMarineTech
    id: CMDogtagCombatTech

- type: startingGear
  id: CMGearCombatTechEquipped
  equipment:
    jumpsuit: CMJumpsuitMarineEngineer
    back: CMSatchelMarineTech
    shoes: CMBootsBlackFilled
    eyes: ClothingEyesGlassesMeson
    head: CMArmorHelmetM10Tech
    outerClothing: CMArmorM3Medium
    gloves: CMHandsInsulated
    id: CMDogtagCombatTech
    ears: CMHeadsetAlphaEngineer
    belt: CMBeltUtilityCombatFilled

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointCombatTech
  name: combat tech spawn point
  components:
  - type: SpawnPoint
    job_id: CMCombatTech
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: combat_tech

- type: playTimeTracker
  id: CMJobCombatTech
