- type: job
  parent: CMJobSquadBase
  id: CMSmartgunner
  name: cm-job-name-smartgunner
  description: cm-job-description-smartgunner
  playTimeTracker: CMJobSmartgunner
  requirements:
    - !type:DepartmentTimeRequirement
      department: CMSquad
      time: 18000 # 5 hours
  startingGear: CMGearSmartgunner
  icon: "CMJobIconSmartgunner"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-sl
  accessGroups:
  - Smartgunner
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      firearms: 1
      jtac: 1
      smartgun: 1
    - type: CMVendorUser
      points: 45
  hidden: true # TODO CM14

- type: startingGear
  id: CMGearSmartgunner
  equipment:
    jumpsuit: JumpsuitMarine # TODO CM14 all squad roles should spawn with no jumpsuit but still have clothes on
    back: CMSatchelMarine
    id: CMDogtagSmartgunner

- type: startingGear
  id: CMGearSmartgunnerEquipped
  equipment:
    jumpsuit: JumpsuitMarine
    back: CMSatchelMarine
    shoes: CMBootsBlackFilled
    head: ArmorHelmetM10
    outerClothing: CMArmorM3Medium
    gloves: CMHandsBlackMarine
    id: CMDogtagSmartgunner
    ears: CMHeadsetAlpha

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointSmartGunner
  name: smartgunner spawn point
  components:
  - type: SpawnPoint
    job_id: CMSmartgunner
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: smartgunner

- type: playTimeTracker
  id: CMJobSmartgunner
