- type: job
  parent: CMJobSquadBase
  id: CMSquadLeader
  name: cm-job-name-squad-leader
  description: cm-job-description-squad-leader
  playTimeTracker: CMJobSquadLeader
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMSquad
    time: 36000 # 10 hours
  startingGear: CMGearSquadLeader
  icon: "CMJobIconSquadLeader"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-co
  accessGroups:
  - SquadLeader
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      construction: 2
      cqc: 1
      endurance: 2
      engineer: 2
      firearms: 1
      fireman: 1
      intel: 1
      jtac: 2
      leadership: 1
      medical: 1
      vehicle: 1
    - type: CMVendorUser
      points: 45
    - type: MarineOrders

- type: startingGear
  id: CMGearSquadLeader
  equipment:
    jumpsuit: JumpsuitMarine # TODO CM14 all squad roles should spawn with no jumpsuit but still have clothes on
    back: CMSatchelMarine
    id: CMDogtagSquadLeader

- type: startingGear
  id: CMGearSquadLeaderEquipped
  equipment:
    jumpsuit: JumpsuitMarine
    back: CMSatchelMarine
    shoes: CMBootsBlackFilled
    head: CMArmorHelmetM11
    outerClothing: CMArmorM3Medium
    gloves: CMHandsBlackMarine
    id: CMDogtagSquadLeader
    ears: CMHeadsetAlphaLeader

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointSquadLeader
  name: squad leader spawn point
  components:
  - type: SpawnPoint
    job_id: CMSquadLeader
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: squad_leader

- type: playTimeTracker
  id: CMJobSquadLeader
