- type: job
  parent: CMJobSquadBase
  id: CMWeaponsSpecialist
  name: cm-job-name-weapons-specialist
  description: cm-job-description-weapons-specialist
  playTimeTracker: CMJobWeaponsSpecialist
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMSquad
    time: 18000 # 5 hours
  startingGear: CMGearWeaponsSpecialist
  icon: "CMJobIconWeaponsSpecialist"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-sl
  accessGroups:
  - WeaponSpec
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      cqc: 1
      construction: 1
      endurance: 2
      engineer: 1
      firearms: 1
      jtac: 1
      meleeWeapons: 1
      specialistWeapons: 1
    - type: CMVendorUser
      points: 45
      extraPoints:
        Specialist: 120

- type: startingGear
  id: CMGearWeaponsSpecialist
  equipment:
    jumpsuit: JumpsuitMarine # TODO CM14 all squad roles should spawn with no jumpsuit but still have clothes on
    back: CMSatchelMarine
    id: CMDogtagWeaponsSpecialist

- type: startingGear
  id: CMGearWeaponsSpecialistEquipped
  equipment:
    jumpsuit: JumpsuitMarine
    back: CMSatchelMarine
    shoes: CMBootsBlackFilled
    head: ArmorHelmetM10
    outerClothing: CMArmorM3Medium
    gloves: CMHandsBlackMarine
    id: CMDogtagWeaponsSpecialist
    ears: CMHeadsetAlpha

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointWeaponsSpecialist
  name: weapons specialist spawn point
  components:
  - type: SpawnPoint
    job_id: CMWeaponsSpecialist
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: weapons_specialist

- type: playTimeTracker
  id: CMJobWeaponsSpecialist
