- type: job
  parent: CMJobBase
  id: CMCorrespondent
  name: cm-job-name-correspondent
  description: cm-job-description-correspondent
  playTimeTracker: CMJobCorrespondent
  requirements:
  - !type:TotalDepartmentsTimeRequirement
    group: CMDepartmentsHuman
    time: 36000 # 10 hours
  startingGear: CMGearCorrespondent
  icon: "CMJobIconEmpty"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-co
  accessGroups:
  - CMCorrespondent
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      firearms: 0
      vehicles: 1
  hasIcon: false

- type: startingGear
  id: CMGearCorrespondent
  equipment:
    jumpsuit: CMJumpsuitCorrespondent
    outerClothing: CMCoatCorrespondent
    shoes: CMShoesLaceup
    id: CMIDCardCorrespondent
    ears: CMHeadsetReporter
    #    belt: CMCamera TODO CM14
    pocket1: CMPouchGeneralLarge

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointCorrespondent
  name: correspondent spawn point
  components:
  - type: SpawnPoint
    job_id: CMCorrespondent
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: combat_correspondent

- type: playTimeTracker
  id: CMJobCorrespondent
