- type: job
  parent: CMJobBase
  id: CMPilotGunship
  name: cm-job-name-gunship-pilot
  description: cm-job-description-gunship-pilot
  playTimeTracker: CMJobPilotGunship
  requirements:
  - !type:TotalJobsTimeRequirement
    group: CMJobsDropship
    time: 7200 # 2 hours
  startingGear: CMGearPilotGunship
  icon: "CMJobIconPilotGunship"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-aso
  accessGroups:
  - Pilot
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      firearms: 1
      intel: 1
      jtac: 2
      leadership: 1
      medical: 2
      overwatch: 1
      pilot: 2
      powerLoader: 2
      surgery: 1
    - type: MarineOrders
  hidden: true # TODO CM14

- type: startingGear
  id: CMGearPilotGunship
  equipment:
    jumpsuit: CMJumpsuitPilot
    back: CMSatchel
    shoes: CMBootsBlackFilled
    id: CMIDCardPilotGunship
    ears: CMHeadsetPilot

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointPilotGunship
  name: gunship pilot spawn point
  components:
  - type: SpawnPoint
    job_id: CMPilotGunship
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: pilot

- type: playTimeTracker
  id: CMJobPilotGunship
