- type: job
  parent: CMJobBase
  id: CMChiefEngineer
  name: cm-job-name-chief-engineer
  description: cm-job-description-chief-engineer
  playTimeTracker: CMJobChiefEngineer
  requirements:
  - !type:TotalJobsTimeRequirement
    group: CMJobsEngineering
    time: 36000 # 10 hours
  weight: 5
  startingGear: CMGearChiefEngineer
  icon: "CMJobIconChiefEngineer"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-aso
  accessGroups:
  - CMCE
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      construction: 3
      engineer: 3
      firearms: 1
      fireman: 1
      intel: 1
      jtac: 4
      leadership: 3
      navigations: 1
      overwatch: 1
      police: 1
      powerLoader: 2
    - type: MarineOrders
  hidden: true # TODO CM14

- type: startingGear
  id: CMGearChiefEngineer
  equipment:
    jumpsuit: CMJumpsuitChiefEngineer
    back: CMSatchelMarineTech
    shoes: CMBootsBlack
    gloves: CMHandsInsulated
    id: CMIDCardChiefEngineer
    ears: CMHeadsetCE
    belt: CMBeltUtilityFilled
    pocket1: CMPouchElectronics

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointChiefEngineer
  name: chief engineer spawn point
  components:
  - type: SpawnPoint
    job_id: CMChiefEngineer
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: chief_engineer

- type: playTimeTracker
  id: CMJobChiefEngineer
