- type: job
  parent: CMJobBase
  id: CMMaintTech
  name: cm-job-name-maint-tech
  description: cm-job-description-maint-tech
  playTimeTracker: CMJobMaintTech
  startingGear: CMGearMaintTech
  icon: "CMJobIconMaintTech"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-ce
  accessGroups:
  - MaintTech
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      domestics: 1
      construction: 3
      engineer: 3
      firearms: 1
      powerLoader: 2
  hidden: true # TODO CM14

- type: startingGear
  id: CMGearMaintTech
  equipment:
    jumpsuit: CMJumpsuitMaintTech
    back: CMSatchelMarineTech
    shoes: CMBootsBlack
    gloves: CMHandsInsulated
    id: CMIDCardMaintTech
    ears: CMHeadsetEngineer
    #    belt: TODO CM14 M276 Pattern General Pistol Holster Rig Filled
    pocket2: CMPouchGeneralMedium

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointMaintTech
  name: maint tech spawn point
  components:
  - type: SpawnPoint
    job_id: CMMaintTech
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: maintenance_tech

- type: playTimeTracker
  id: CMJobMaintTech
