- type: job
  id: CMOrdnanceTech
  parent: CMJobBase
  name: cm-job-name-ordnance-tech
  description: cm-job-description-ordnance-tech
  playTimeTracker: CMJobOrdnanceTech
  requirements:
  - !type:TotalJobsTimeRequirement
    group: CMJobsEngineering
    time: 3600 # 1 hour
  startingGear: CMGearOrdnanceTech
  icon: "CMJobIconOrdnanceTech"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-ce
  accessGroups:
  - OT
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      construction: 3
      engineer: 3
      firearms: 1
      powerLoader: 2
  hidden: true # TODO CM14

- type: startingGear
  id: CMGearOrdnanceTech
  equipment:
    jumpsuit: CMJumpsuitOrdnanceTech
    back: CMSatchelMarineTech
    shoes: CMBootsBlack
    gloves: CMHandsInsulated
    id: CMIDCardOrdnanceTech
    ears: CMHeadsetEngineer
    belt: CMBeltUtilityFilled
#    pocket1: CMDemolitionsScanner TODO CM14
    pocket2: CMPouchGeneralMedium

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointOrdnanceTech
  name: ordnance tech spawn point
  components:
  - type: SpawnPoint
    job_id: CMOrdnanceTech
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: ordnance_tech

- type: playTimeTracker
  id: CMJobOrdnanceTech
